#!/bin/sh

if [ -n "$USERID" ] && [ -n "$GROUPID" ] ; then
  sudo -u user -g group -- s3cmd -c /.s3cfg sync --delete-removed "$S3_DIRECTORY" "$S3_URL"
else
  s3cmd -c /.s3cfg sync --delete-removed "$S3_DIRECTORY" "$S3_URL"
fi
