#!/bin/sh

if [ -n "$USERID" ] && [ -n "$GROUPID" ] ; then
  createuser
  sudo -u user -g group -- s3cmd -c /.s3cfg sync "$S3_URL" "$S3_DIRECTORY"
else
  s3cmd -c /.s3cfg sync "$S3_URL" "$S3_DIRECTORY"
fi
