#!/bin/sh

trap "exit 0" INT TERM EXIT

cfg || exit 4

if [ -n "$USERID" ] && [ -n "$GROUPID" ] ; then
  createuser
fi

inotifywait -mr "$S3_DIRECTORY" -e close_write |
    while read path action file; do
      push
    done
