#!/bin/sh

if [ ! -z "$USERID" -a ! -z "$GROUPID" ] ; then
  createuser
  sudo -u user -g group -- s3cmd sync $S3_URL "$S3_DIRECTORY"
else
  echo "Warning: USERID and GROUPID not set. Files will be pushed with UID/GID metadata and pulled at startup as root:root."
fi

inotifywait -mr "$S3_DIRECTORY" -e close_write |
    while read path action file; do
      push
    done
